<a href="https://colab.research.google.com/github/ShiaMicaNaomiOnix/Crime-/blob/main/%EA%B2%BD%EC%B0%B0%EC%B2%AD_2017_2023%EB%85%84%EA%B9%8C%EC%A7%80%EC%9D%98_%EC%82%AC%EC%9D%B4%EB%B2%84%EB%B2%94%EC%A3%84_%EB%B0%9C%EC%83%9D%EA%B2%80%EC%88%98%EC%99%80_%EA%B2%80%EA%B1%B0%EA%B1%B4%EC%88%98_%EA%B0%80%EA%B3%B5%EB%8D%B0%EC%9D%B4%ED%84%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
with open('경찰청_사이버사기범죄 현황_20241231.csv', encoding = 'EUC-KR') as f:
  print(f.readline())
  print(f.readline())

연도,구분,직거래,쇼핑몰,게임,이메일 무역,연예빙자,사이버투자,사이버사기_기타

2024,발생건수,100539,7760,9077,202,2253,12851,95752

In [ ]:
with open('경찰청_연도별 사이버 범죄 통계 현황_20231231.csv', encoding = 'EUC-KR') as f:
  print(f.readline())
  print(f.readline())

연도,구분,해킹_계정도용,해킹_단순침입,해킹_자료유출,해킹_자료훼손,서비스거부공격,악성프로그램_랜섬웨어,악성프로그램_기타,기타 정보통신망 침해형 범죄,사이버사기_직거래,사이버사기_쇼핑몰,사이버사기_게임,사이버사기_이메일 무역사기,사이버사기_기타,사이버금융범죄_피싱,사이버금융범죄_파밍,사이버금융범죄_스미싱,사이버금융범죄_메모리해킹,사이버금융범죄_메신저이용사기,사이버금융범죄_기타,개인위치정보 침해,사이버저작권침해,기타 정보통신망 이용형 범죄,사이버 음란물_일반음란물,사이버 음란물_아동음란물,사이버 음란물_불법촬영물유포,사이버 도박_스포츠토토,사이버 도박_경마 경륜 경정,사이버 도박_카지노,사이버 도박_기타,사이버 명예훼손_모욕,사이버 스토킹,기타 불법 컨텐츠

2023,발생건수,877,1424,172,223,75,71,233,1148,78320,5156,8331,222,75659,3645,38,1673,19,13179,4501,256,8727,3653,381,1052,701,1204,620,357,1255,24252,0,693

In [ ]:
import pandas as pd
df = pd.read_csv('경찰청_사이버사기범죄 현황_20241231.csv', encoding = 'EUC-KR')
df

      연도    구분     직거래   쇼핑몰    게임  이메일 무역  연예빙자  사이버투자  사이버사기_기타
0   2024  발생건수  100539  7760  9077     202  2253  12851     95752
1   2024  검거건수   62342  4026  6234      23   470   3899     41115
2   2023  발생건수   78320  5156  8331     222     0      0     75659
3   2023  검거건수   52997  2892  5510       8     0      0     35836
4   2022  발생건수   79052  2254  8579     260     0      0     65570
5   2022  검거건수   63417  1647  6353      14     0      0     37819
6   2021  발생건수   84107  1570  8147     243     0      0     47087
7   2021  검거건수   66134  1162  6438      14     0      0     28202
8   2020  발생건수  123168  1821  9109     324     0      0     39906
9   2020  검거건수   93690  1570  6727      20     0      0     25226
10  2019  발생건수   89797   960  7687     305     0      0     37325
11  2019  검거건수   72935   793  6183      23     0      0     25717
12  2018  발생건수   74044   647  9380     367     0      0     27562
13  2018  검거건수   60224   526  7545      29     0      0     19390
14  2017  발생건수   67589   560  7227     187     0      0     17073
15  2017  검거건수   60502   476  6150      19     0      0     13593

In [ ]:
df_filtered = df[(df['연도'].between(2017, 2023)) & (df['구분'].isin(['발생건수', '검거건수']))]
display(df_filtered)

      연도    구분     직거래   쇼핑몰    게임  이메일 무역  연예빙자  사이버투자  사이버사기_기타
2   2023  발생건수   78320  5156  8331     222     0      0     75659
3   2023  검거건수   52997  2892  5510       8     0      0     35836
4   2022  발생건수   79052  2254  8579     260     0      0     65570
5   2022  검거건수   63417  1647  6353      14     0      0     37819
6   2021  발생건수   84107  1570  8147     243     0      0     47087
7   2021  검거건수   66134  1162  6438      14     0      0     28202
8   2020  발생건수  123168  1821  9109     324     0      0     39906
9   2020  검거건수   93690  1570  6727      20     0      0     25226
10  2019  발생건수   89797   960  7687     305     0      0     37325
11  2019  검거건수   72935   793  6183      23     0      0     25717
12  2018  발생건수   74044   647  9380     367     0      0     27562
13  2018  검거건수   60224   526  7545      29     0      0     19390
14  2017  발생건수   67589   560  7227     187     0      0     17073
15  2017  검거건수   60502   476  6150      19     0      0     13593

In [ ]:
import pandas as pd
df2 = pd.read_csv('경찰청_연도별 사이버 범죄 통계 현황_20231231.csv', encoding = 'EUC-KR')
df2.head()

,연도,구분,해킹_계정도용,해킹_단순침입,해킹_자료유출,해킹_자료훼손,서비스거부공격,악성프로그램_랜섬웨어,악성프로그램_기타,기타 정보통신망 침해형 범죄,...,사이버 음란물_일반음란물,사이버 음란물_아동음란물,사이버 음란물_불법촬영물유포,사이버 도박_스포츠토토,사이버 도박_경마 경륜 경정,사이버 도박_카지노,사이버 도박_기타,사이버 명예훼손_모욕,사이버 스토킹,기타 불법 컨텐츠
0,2023,발생건수,877,1424,172,223,75,71,233,1148,...,381,1052,701,1204,620,357,1255,24252,0,693
1,2023,검거건수,100,409,86,86,22,2,74,405,...,257,918,469,1189,559,343,1134,20390,0,264
2,2022,발생건수,896,1181,103,216,30,90,95,883,...,764,1052,1225,1395,457,123,1021,29258,0,447
3,2022,검거건수,98,193,41,65,7,3,41,281,...,508,943,809,1358,411,108,961,18242,0,268
4,2021,발생건수,1391,1090,110,248,14,58,99,835,...,1091,1747,1355,3415,222,260,1608,28988,0,436

In [ ]:
df2_filtered = df2[(df2['연도'].between(2017, 2023)) & (df2['구분'].isin(['발생건수', '검거건수']))]
display(df2_filtered)

,연도,구분,해킹_계정도용,해킹_단순침입,해킹_자료유출,해킹_자료훼손,서비스거부공격,악성프로그램_랜섬웨어,악성프로그램_기타,기타 정보통신망 침해형 범죄,...,사이버 음란물_일반음란물,사이버 음란물_아동음란물,사이버 음란물_불법촬영물유포,사이버 도박_스포츠토토,사이버 도박_경마 경륜 경정,사이버 도박_카지노,사이버 도박_기타,사이버 명예훼손_모욕,사이버 스토킹,기타 불법 컨텐츠
0,2023,발생건수,877,1424,172,223,75,71,233,1148,...,381,1052,701,1204,620,357,1255,24252,0,693
1,2023,검거건수,100,409,86,86,22,2,74,405,...,257,918,469,1189,559,343,1134,20390,0,264
2,2022,발생건수,896,1181,103,216,30,90,95,883,...,764,1052,1225,1395,457,123,1021,29258,0,447
3,2022,검거건수,98,193,41,65,7,3,41,281,...,508,943,809,1358,411,108,961,18242,0,268
4,2021,발생건수,1391,1090,110,248,14,58,99,835,...,1091,1747,1355,3415,222,260,1608,28988,0,436
5,2021,검거건수,658,178,40,65,6,12,53,242,...,790,1646,994,3320,212,251,1433,17243,0,321
6,2020,발생건수,1067,1621,130,358,25,24,145,974,...,1366,2623,842,3222,332,429,1709,19388,42,204
7,2020,검거건수,117,217,46,168,10,0,81,272,...,987,2398,678,3154,315,382,1585,12638,39,126
8,2019,발생건수,751,1458,114,341,35,24,246,669,...,1769,756,165,3078,366,366,1536,16633,25,251
9,2019,검거건수,118,277,41,120,14,0,189,248,...,1436,589,139,3017,352,353,1440,11632,20,176
10,2018,발생건수,721,1003,114,340,20,33,86,571,...,2661,1172,0,1629,276,176,931,15926,60,208
11,2018,검거건수,160,241,41,142,14,1,49,254,...,2250,1032,0,1599,257,167,924,10889,50,137
12,2017,발생건수,1160,904,67,299,43,11,156,516,...,2043,603,0,3169,211,227,1523,13348,59,124
13,2017,검거건수,619,219,36,116,28,1,121,258,...,1794,535,0,3127,205,228,1520,9756,52,95

In [ ]:
print(df.columns)
print(df2.columns)

Index(['연도', '구분', '직거래', '쇼핑몰', '게임', '이메일 무역', '연예빙자', '사이버투자', '사이버사기_기타'], dtype='object')
Index(['연도', '구분', '해킹_계정도용', '해킹_단순침입', '해킹_자료유출', '해킹_자료훼손', '서비스거부공격',
       '악성프로그램_랜섬웨어', '악성프로그램_기타', '기타 정보통신망 침해형 범죄', '사이버사기_직거래', '사이버사기_쇼핑몰',
       '사이버사기_게임', '사이버사기_이메일 무역사기', '사이버사기_기타', '사이버금융범죄_피싱', '사이버금융범죄_파밍',
       '사이버금융범죄_스미싱', '사이버금융범죄_메모리해킹', '사이버금융범죄_메신저이용사기', '사이버금융범죄_기타',
       '개인위치정보 침해', '사이버저작권침해', '기타 정보통신망 이용형 범죄', '사이버 음란물_일반음란물',
       '사이버 음란물_아동음란물', '사이버 음란물_불법촬영물유포', '사이버 도박_스포츠토토', '사이버 도박_경마 경륜 경정',
       '사이버 도박_카지노', '사이버 도박_기타', '사이버 명예훼손_모욕', '사이버 스토킹', '기타 불법 컨텐츠'],
      dtype='object')

In [ ]:
import pandas as pd

file1 = '경찰청_연도별 사이버 범죄 통계 현황_20231231.csv'
file2 = '경찰청_사이버사기범죄 현황_20241231.csv'

#1.데이터 로드
df1 = pd.read_csv(file1, encoding = 'EUC-KR')
df2 = pd.read_csv(file2, encoding = 'EUC-KR')

#칼럼명 앞뒤의 공백 제거
df1.columns = df1.columns.str.strip()
df2.columns = df2.columns.str.strip()

#2.2017~2023년 데이터 필터링
df1_filtered = df1[(df1['연도'] >=2017) & (df1['연도'] <=2023)].copy()
df2_filtered = df2[(df2['연도'] >=2017) & (df2['연도'] <=2023)].copy()

# [추가] 두 데이터프레임을 하나로 통합 (행 방향으로 합치기)
df_filtered = pd.concat([df1_filtered, df2_filtered], ignore_index=False)

#3.연애빙자/사이버투자 관련행 제외
df_filtered = df_filtered[~df_filtered['구분'].str.contains('연애|연예|투자', na = False)].copy()


#4.그룹별로 묶을 컬럼 리스트 정의
hacking_cols = ['해킹_계정도용', '해킹_단순침입', '해킹_자료유출', '해킹_자료훼손']
scam_cols = ['직거래', '쇼핑몰', '게임', '이메일 무역', '사이버사기_직거래', '사이버사기_쇼핑몰',
       '사이버사기_게임', '사이버사기_이메일 무역사기']
cyber_cols = ['사이버금용범죄_피싱', '사이버금용범죄_메신저이용사기', '사이버금용범죄_기타', '사이버 음란물_아동음란물', '사이버 음란물_불법촬영물유포', '사이버 도박_스포츠토토', '사이버 도박_경마 경륜 경정',
       '사이버 도박_카지노', '사이버 도박_기타', '사이버 명예훼손_모욕', '사이버 스토킹']
Others_cols = ['사이버사기_기타', '기타 불법 컨텐츠']

#5. 데이터프레임에 실제로 존재하는 컬럼만 필터링
hacking_present = [c for c in hacking_cols if c in df_filtered.columns]
scam_present = [c for c in scam_cols if c in df_filtered.columns]
cyber_present = [c for c in cyber_cols if c in df_filtered.columns]
Others_present = [c for c in Others_cols if c in df_filtered.columns]


#그룹별 합산
df_filtered['Hacking'] = df_filtered[hacking_present].fillna(0).sum(axis=1) if hacking_present else 0
df_filtered['Scam'] = df_filtered[scam_present].fillna(0).sum(axis=1) if scam_present else 0
df_filtered['Cyber'] = df_filtered[cyber_present].fillna(0).sum(axis=1) if cyber_present else 0
df_filtered['Others'] = df_filtered[Others_present].fillna(0).sum(axis=1) if Others_present else 0

group_df = df_filtered.groupby(['연도', '구분'])[['Hacking', 'Scam', 'Cyber', 'Others']].sum().reset_index()

#6.새로운 통합 영문 데이터프레인 생성
mixing_df = pd.DataFrame()
mixing_df['Year'] = group_df['연도']
mixing_df['Type'] = group_df['구분']
mixing_df['Hacking'] =group_df['Hacking']
mixing_df['Scam'] = group_df['Scam']
mixing_df['Cyber'] = group_df['Cyber']
mixing_df['Others'] = group_df['Others']


#통합 컬럼 생성
#mixing_df['Year_Type'] = mixing_df['Year'].astype(str) + '_' + mixing_df['Type'].astype(str)
#8.정렬 수행
#mixing_df = mixing_df.sort_values(by = ['Year', 'Type'], ascending = [False, True]).reset_index(drop = True)

#9.최종적으로 필요한 컬럼만 슬라이싱
final_cols = ['Year','Type', 'Hacking', 'Scam', 'Cyber', 'Others']
mixing_df = mixing_df[final_cols]

#10. CSV 파일로 저장
mixing_df.to_csv("경찰청_사이버범죄_대그룹_통합_추출.csv", index = False, encoding = 'EUC-KR')

#결과
display(mixing_df)

    Year  Type  Hacking      Scam    Cyber    Others
0   2017  검거건수    990.0  134294.0  15423.0   27281.0
1   2017  발생건수   2430.0  151126.0  19140.0   34270.0
2   2018  검거건수    584.0  136648.0  14918.0   38917.0
3   2018  발생건수   2178.0  168876.0  20170.0   55332.0
4   2019  검거건수    556.0  159868.0  17542.0   51610.0
5   2019  발생건수   2664.0  197498.0  22925.0   74901.0
6   2020  검거건수    548.0  204014.0  21189.0   50578.0
7   2020  발생건수   3176.0  268844.0  28587.0   80016.0
8   2021  검거건수    941.0  147496.0  25099.0   56725.0
9   2021  발생건수   2839.0  188134.0  37595.0   94610.0
10  2022  검거건수    397.0  142862.0  22832.0   75906.0
11  2022  발생건수   2396.0  180290.0  34531.0  131587.0
12  2023  검거건수    681.0  122814.0  25002.0   71936.0
13  2023  발생건수   2696.0  184058.0  29441.0  152011.0

In [ ]:
#발생건수만 입력
#1. 원하는 유형 선택
target_type = '발생건수'
#2. 이미 있는 mixing_df에서 필터링
filtered_result = mixing_df[mixing_df['Type'].str.contains(target_type)].reset_index(drop = True)

#3.파일 저장
filtered_result.to_csv(f'경찰청_사이버범죄_대그룹_통합_{target_type}.csv', index = False, encoding = 'EUC-KR')
display(filtered_result)

   Year  Type  Hacking      Scam    Cyber    Others
0  2017  발생건수   2430.0  151126.0  19140.0   34270.0
1  2018  발생건수   2178.0  168876.0  20170.0   55332.0
2  2019  발생건수   2664.0  197498.0  22925.0   74901.0
3  2020  발생건수   3176.0  268844.0  28587.0   80016.0
4  2021  발생건수   2839.0  188134.0  37595.0   94610.0
5  2022  발생건수   2396.0  180290.0  34531.0  131587.0
6  2023  발생건수   2696.0  184058.0  29441.0  152011.0

In [ ]:
#검거건수만 입력
#1. 원하는 유형 선택
target_type = '검거건수'
#2. 이미 있는 mixing_df에서 필터링
filtered_result = mixing_df[mixing_df['Type'].str.contains(target_type)].reset_index(drop = True)

#3.파일 저장
filtered_result.to_csv(f'경찰청_사이버범죄_대그룹_통합_{target_type}.csv', index = False, encoding = 'EUC-KR')
display(filtered_result)

   Year  Type  Hacking      Scam    Cyber   Others
0  2017  검거건수    990.0  134294.0  15423.0  27281.0
1  2018  검거건수    584.0  136648.0  14918.0  38917.0
2  2019  검거건수    556.0  159868.0  17542.0  51610.0
3  2020  검거건수    548.0  204014.0  21189.0  50578.0
4  2021  검거건수    941.0  147496.0  25099.0  56725.0
5  2022  검거건수    397.0  142862.0  22832.0  75906.0
6  2023  검거건수    681.0  122814.0  25002.0  71936.0

In [ ]:
import pandas as pd

# 1. 파일 이름 정의
file1 = '경찰청_연도별 사이버 범죄 통계 현황_20231231.csv'
file2 = '경찰청_사이버사기범죄 현황_20241231.csv'

# 2. 데이터 로드
df1 = pd.read_csv(file1, encoding='EUC-KR')
df2 = pd.read_csv(file2, encoding='EUC-KR')

# 3. 컬럼명 앞뒤 공백 제거
df1.columns = df1.columns.str.strip()
df2.columns = df2.columns.str.strip()

# 4. 2017~2023년 데이터 필터링
df1_filtered = df1[(df1['연도'] >= 2017) & (df1['연도'] <= 2023)].copy()
df2_filtered = df2[(df2['연도'] >= 2017) & (df2['연도'] <= 2023)].copy()

# 5. 두 파일의 데이터 결합
df_filtered = pd.concat([df1_filtered, df2_filtered], ignore_index=True)

# 6. '구분' 컬럼 앞뒤 공백 제거 및 특정 행 제외
df_filtered['구분'] = df_filtered['구분'].astype(str).str.strip()
df_filtered = df_filtered[~df_filtered['구분'].str.contains('연애|연예|투자', na=False)].copy()

# 7. 년도와 구분 기준으로 중복 행 원천 합산
df_grouped = df_filtered.groupby(['연도', '구분']).sum().reset_index()


# 8. 대그룹 컬럼 리스트 정의 및 반영
hacking_cols = ['해킹_계정도용', '해킹_단순침입', '해킹_자료유출', '해킹_자료훼손']
scam_cols = ['직거래', '쇼핑몰', '게임', '이메일 무역', '사이버사기_직거래', '사이버사기_쇼핑몰', '사이버사기_게임', '사이버사기_이메일 무역사기']
cyber_cols = ['사이버금용범죄_피싱', '사이버금용범죄_메신저이용사기', '사이버금용범죄_기타', '사이버금융범죄_피싱', '사이버금융범죄_메신저이용사기', '사이버금융범죄_기타',
              '사이버 음란물_아동음란물', '사이버 음란물_불법촬영물유포', '사이버 도박_스포츠토토', '사이버 도박_경마 경륜 경정',
              '사이버 도박_카지노', '사이버 도박_기타', '사이버 명예훼손_모욕', '사이버 스토킹']
Others_cols = ['사이버사기_기타', '기타 불법 컨텐츠']

hacking_present = [c for c in hacking_cols if c in df_grouped.columns]
scam_present = [c for c in scam_cols if c in df_grouped.columns]
cyber_present = [c for c in cyber_cols if c in df_grouped.columns]
Others_present = [c for c in Others_cols if c in df_grouped.columns]

mixing_df = pd.DataFrame()
mixing_df['년도'] = df_grouped['연도']
mixing_df['구분'] = df_grouped['구분']

mixing_df['Hacking'] = df_grouped[hacking_present].fillna(0).sum(axis=1) if hacking_present else 0
mixing_df['Scam'] = df_grouped[scam_present].fillna(0).sum(axis=1) if scam_present else 0
mixing_df['Cyber'] = df_grouped[cyber_present].fillna(0).sum(axis=1) if cyber_present else 0
mixing_df['Others'] = df_grouped[Others_present].fillna(0).sum(axis=1) if Others_present else 0


# 9. 세로형 변환 (Melt)
final_melted = mixing_df.melt(
    id_vars=['구분', '년도'],
    value_vars=['Hacking', 'Scam', 'Cyber', 'Others'],
    var_name='범죄종류',
    value_name='값'
)

# 10. 정렬 기준 설정 (년도 내림차순, 구분 오름차순, 범죄종류 순서 제어)
# 이미지와 똑같이 Hacking -> Scam -> Cyber -> Others 순서로 고정하기 위해 카테고리 지정
final_melted['범죄종류'] = pd.Categorical(final_melted['범죄종류'], categories=['Hacking', 'Scam', 'Cyber', 'Others'], ordered=True)
final_melted = final_melted.sort_values(by=['년도', '구분', '범죄종류'], ascending=[False, True, True]).reset_index(drop=True)


# ⭐⭐⭐ [핵심 변경: 원하시는 엑셀 그룹화/병합 형태로 레이아웃 수정] ⭐⭐⭐
# 구분과 년도를 행 인덱스로 설정하여 엑셀에서 그룹으로 묶이게 만듭니다.
final_excel_format = final_melted.set_index(['구분', '년도', '범죄종류'])


# 11. 엑셀에서 열었을 때 가장 깨끗하게 보이는 인코딩(utf-8-sig)으로 저장
final_excel_format.to_csv("경찰청_사이버범죄_대그룹_원하는모양.csv", encoding='utf-8-sig')

# 결과 출력
display(final_excel_format)

                          값
구분   년도   범죄종류
검거건수 2023 Hacking     681.0
          Scam     122814.0
          Cyber     30329.0
          Others    71936.0
발생건수 2023 Hacking    2696.0
          Scam     184058.0
          Cyber     50766.0
          Others   152011.0
검거건수 2022 Hacking     397.0
          Scam     142862.0
          Cyber     28997.0
          Others    75906.0
발생건수 2022 Hacking    2396.0
          Scam     180290.0
          Cyber     57931.0
          Others   131587.0
검거건수 2021 Hacking     941.0
          Scam     147496.0
          Cyber     30657.0
          Others    56725.0
발생건수 2021 Hacking    2839.0
          Scam     188134.0
          Cyber     61315.0
          Others    94610.0
검거건수 2020 Hacking     548.0
          Scam     204014.0
          Cyber     25226.0
          Others    50578.0
발생건수 2020 Hacking    3176.0
          Scam     268844.0
          Cyber     45392.0
          Others    80016.0
검거건수 2019 Hacking     556.0
          Scam     159868.0
          Cyber     20377.0
          Others    51610.0
발생건수 2019 Hacking    2664.0
          Scam     197498.0
          Cyber     31380.0
          Others    74901.0
검거건수 2018 Hacking     584.0
          Scam     136648.0
          Cyber     16711.0
          Others    38917.0
발생건수 2018 Hacking    2178.0
          Scam     168876.0
          Cyber     23890.0
          Others    55332.0
검거건수 2017 Hacking     990.0
          Scam     134294.0
          Cyber     16686.0
          Others    27281.0
발생건수 2017 Hacking    2430.0
          Scam     151126.0
          Cyber     21360.0
          Others    34270.0

In [ ]:
import pandas as pd

# 1. 파일 이름 정의
file1 = '경찰청_연도별 사이버 범죄 통계 현황_20231231.csv'
file2 = '경찰청_사이버사기범죄 현황_20241231.csv'

# 2. 데이터 로드 (한글 깨짐 방지를 위해 EUC-KR 적용)
df1 = pd.read_csv(file1, encoding='EUC-KR')
df2 = pd.read_csv(file2, encoding='EUC-KR')

# 3. 컬럼명 앞뒤의 공백 제거
df1.columns = df1.columns.str.strip()
df2.columns = df2.columns.str.strip()

# 4. 2017~2023년 데이터 필터링
df1_filtered = df1[(df1['연도'] >= 2017) & (df1['연도'] <= 2023)].copy()
df2_filtered = df2[(df2['연도'] >= 2017) & (df2['연도'] <= 2023)].copy()

# 5. 두 파일의 데이터를 하나로 결합
df_filtered = pd.concat([df1_filtered, df2_filtered], ignore_index=True)

# 6. '구분' 컬럼의 데이터 자체 앞뒤 공백 청소 및 불필요한 행(연애/투자) 제외
df_filtered['구분'] = df_filtered['구분'].astype(str).str.strip()
df_filtered = df_filtered[~df_filtered['구분'].str.contains('연애|연예|투자', na=False)].copy()

# 7. 두 파일의 데이터가 겹쳐서 수치가 부풀려지거나 중복 행이 생기지 않도록 원천 합산(통합)
df_grouped = df_filtered.groupby(['연도', '구분']).sum().reset_index()


# 8. 대그룹으로 묶을 컬럼 리스트 정의
hacking_cols = ['해킹_계정도용', '해킹_단순침입', '해킹_자료유출', '해킹_자료훼손']
scam_cols = ['직거래', '쇼핑몰', '게임', '이메일 무역', '사이버사기_직거래', '사이버사기_쇼핑몰', '사이버사기_게임', '사이버사기_이메일 무역사기']
cyber_cols = ['사이버금용범죄_피싱', '사이버금용범죄_메신저이용사기', '사이버금용범죄_기타', '사이버금융범죄_피싱', '사이버금융범죄_메신저이용사기', '사이버금융범죄_기타',
              '사이버 음란물_아동음란물', '사이버 음란물_불법촬영물유포', '사이버 도박_스포츠토토', '사이버 도박_경마 경륜 경정',
              '사이버 도박_카지노', '사이버 도박_기타', '사이버 명예훼손_모욕', '사이버 스토킹']
Others_cols = ['사이버사기_기타', '기타 불법 컨텐츠']

# 데이터프레임에 실제로 존재하는 컬럼만 필터링
hacking_present = [c for c in hacking_cols if c in df_grouped.columns]
scam_present = [c for c in scam_cols if c in df_grouped.columns]
cyber_present = [c for c in cyber_cols if c in df_grouped.columns]
Others_present = [c for c in Others_cols if c in df_grouped.columns]


# 9. 대그룹별 합산 데이터를 담을 가로형 데이터프레임 생성
mixing_df = pd.DataFrame()
mixing_df['년도'] = df_grouped['연도']
mixing_df['구분'] = df_grouped['구분']

mixing_df['Hacking'] = df_grouped[hacking_present].fillna(0).sum(axis=1) if hacking_present else 0
mixing_df['Scam'] = df_grouped[scam_present].fillna(0).sum(axis=1) if scam_present else 0
mixing_df['Cyber'] = df_grouped[cyber_present].fillna(0).sum(axis=1) if cyber_present else 0
mixing_df['Others'] = df_grouped[Others_present].fillna(0).sum(axis=1) if Others_present else 0


# 10. ⭐ 원하시는 엑셀 이미지 구조로 세로 변환 (Melt 처리) ⭐
final_melted = mixing_df.melt(
    id_vars=['구분', '년도'],
    value_vars=['Hacking', 'Scam', 'Cyber', 'Others'],
    var_name='범죄종류',
    value_name='값'
)

# 11. 컬럼 배치 순서 조정 (구분 | 년도 | 범죄종류 | 값)
final_melted = final_melted[['구분', '년도', '범죄종류', '값']]

# 12. 최종 정렬 (년도 내림차순, 구분 오름차순, 범죄종류 오름차순)
final_melted = final_melted.sort_values(by=['년도', '구분', '범죄종류'], ascending=[False, True, True]).reset_index(drop=True)


# 13. 최종 가공 데이터 CSV 파일로 저장
final_melted.to_csv("경찰청_사이버범죄_대그룹_최종통합_세로형.csv", index=False, encoding='EUC-KR')

# 최종 결과물 출력
display(final_melted)

      구분    년도     범죄종류         값
0   검거건수  2023    Cyber   30329.0
1   검거건수  2023  Hacking     681.0
2   검거건수  2023   Others   71936.0
3   검거건수  2023     Scam  122814.0
4   발생건수  2023    Cyber   50766.0
5   발생건수  2023  Hacking    2696.0
6   발생건수  2023   Others  152011.0
7   발생건수  2023     Scam  184058.0
8   검거건수  2022    Cyber   28997.0
9   검거건수  2022  Hacking     397.0
10  검거건수  2022   Others   75906.0
11  검거건수  2022     Scam  142862.0
12  발생건수  2022    Cyber   57931.0
13  발생건수  2022  Hacking    2396.0
14  발생건수  2022   Others  131587.0
15  발생건수  2022     Scam  180290.0
16  검거건수  2021    Cyber   30657.0
17  검거건수  2021  Hacking     941.0
18  검거건수  2021   Others   56725.0
19  검거건수  2021     Scam  147496.0
20  발생건수  2021    Cyber   61315.0
21  발생건수  2021  Hacking    2839.0
22  발생건수  2021   Others   94610.0
23  발생건수  2021     Scam  188134.0
24  검거건수  2020    Cyber   25226.0
25  검거건수  2020  Hacking     548.0
26  검거건수  2020   Others   50578.0
27  검거건수  2020     Scam  204014.0
28  발생건수  2020    Cyber   45392.0
29  발생건수  2020  Hacking    3176.0
30  발생건수  2020   Others   80016.0
31  발생건수  2020     Scam  268844.0
32  검거건수  2019    Cyber   20377.0
33  검거건수  2019  Hacking     556.0
34  검거건수  2019   Others   51610.0
35  검거건수  2019     Scam  159868.0
36  발생건수  2019    Cyber   31380.0
37  발생건수  2019  Hacking    2664.0
38  발생건수  2019   Others   74901.0
39  발생건수  2019     Scam  197498.0
40  검거건수  2018    Cyber   16711.0
41  검거건수  2018  Hacking     584.0
42  검거건수  2018   Others   38917.0
43  검거건수  2018     Scam  136648.0
44  발생건수  2018    Cyber   23890.0
45  발생건수  2018  Hacking    2178.0
46  발생건수  2018   Others   55332.0
47  발생건수  2018     Scam  168876.0
48  검거건수  2017    Cyber   16686.0
49  검거건수  2017  Hacking     990.0
50  검거건수  2017   Others   27281.0
51  검거건수  2017     Scam  134294.0
52  발생건수  2017    Cyber   21360.0
53  발생건수  2017  Hacking    2430.0
54  발생건수  2017   Others   34270.0
55  발생건수  2017     Scam  151126.0

In [ ]:
# 10. 원하시는 구조로 변환하기 위해 데이터를 세로형(Melt)으로 전처리
final_melted = mixing_df.melt(
    id_vars=['구분', '년도'],
    value_vars=['Hacking', 'Scam', 'Cyber', 'Others'],
    var_name='범죄종류',
    value_name='값'
)

# 11. 이미지와 똑같이 Hacking -> Scam -> Cyber -> Others 순서로 고정
final_melted['범죄종류'] = pd.Categorical(final_melted['범죄종류'], categories=['Hacking', 'Scam', 'Cyber', 'Others'], ordered=True)


# ⭐⭐⭐ [진짜 최종 해결책: 엑셀의 피벗 테이블 서식 형태로 정교하게 변환] ⭐⭐⭐

# 12. 판다스의 pivot_table 함수를 이용하여 이미지와 100% 일치하는 레이아웃을 생성합니다.
# 행(Row)에 '구분', '년도', '범죄종류'가 계층형으로 들어가고, 값(Value)에 수치가 들어갑니다.
pivot_result = final_melted.pivot_table(
    index=['구분', '년도', '범죄종류'],
    values='값',
    aggfunc='sum'
)

# 13. 년도는 내림차순(최신순), 구분은 오름차순으로 정렬 기준 정렬
# (MultiIndex 정렬을 통해 2023년 발생/검거 -> 2022년 발생/검거 순으로 이쁘게 정렬됩니다)
pivot_result = pivot_result.sort_index(level=['년도', '구분', '범죄종류'], ascending=[False, True, True])


# ⭐⭐⭐ [중요] .csv 가 아니라 .xlsx(엑셀 파일)로 저장해야 셀 병합 구조가 깨지지 않고 유지됩니다!
file_name = "경찰청_사이버범죄_대그룹_완벽병합형태.xlsx"
pivot_result.to_excel(file_name)

# 결과 출력
display(pivot_result)

/tmp/ipykernel_821/1392551064.py:17: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_result = final_melted.pivot_table(

                          값
구분   년도   범죄종류
검거건수 2023 Hacking     681.0
          Scam     122814.0
          Cyber     30329.0
          Others    71936.0
발생건수 2023 Hacking    2696.0
          Scam     184058.0
          Cyber     50766.0
          Others   152011.0
검거건수 2022 Hacking     397.0
          Scam     142862.0
          Cyber     28997.0
          Others    75906.0
발생건수 2022 Hacking    2396.0
          Scam     180290.0
          Cyber     57931.0
          Others   131587.0
검거건수 2021 Hacking     941.0
          Scam     147496.0
          Cyber     30657.0
          Others    56725.0
발생건수 2021 Hacking    2839.0
          Scam     188134.0
          Cyber     61315.0
          Others    94610.0
검거건수 2020 Hacking     548.0
          Scam     204014.0
          Cyber     25226.0
          Others    50578.0
발생건수 2020 Hacking    3176.0
          Scam     268844.0
          Cyber     45392.0
          Others    80016.0
검거건수 2019 Hacking     556.0
          Scam     159868.0
          Cyber     20377.0
          Others    51610.0
발생건수 2019 Hacking    2664.0
          Scam     197498.0
          Cyber     31380.0
          Others    74901.0
검거건수 2018 Hacking     584.0
          Scam     136648.0
          Cyber     16711.0
          Others    38917.0
발생건수 2018 Hacking    2178.0
          Scam     168876.0
          Cyber     23890.0
          Others    55332.0
검거건수 2017 Hacking     990.0
          Scam     134294.0
          Cyber     16686.0
          Others    27281.0
발생건수 2017 Hacking    2430.0
          Scam     151126.0
          Cyber     21360.0
          Others    34270.0

In [ ]:
import pandas as pd
df3 = pd.read_csv('경찰청_월별 사이버범죄 발생건수와 검거건수 현황_20231231 (1).csv', encoding = 'EUC-KR')
df3.head()

,연도,구분,1월,2월,3월,4월,5월,6월,7월,8월,9월,10월,11월,12월
0,2014,발생건수,4576,5935,9185,9776,9133,10384,9219,9666,10377,12035,9411,10412
1,2014,검거건수,3417,4238,5724,6235,6548,6328,6418,6102,7020,8329,5470,6121
2,2015,발생건수,11129,9223,13506,13794,12245,13650,13548,10904,11382,14617,10011,10670
3,2015,검거건수,6520,5360,9097,9987,9429,10323,9747,8971,8986,12721,6360,7387
4,2016,발생건수,10207,9974,13345,12658,17909,11103,12063,14631,13209,21085,7774,9117

In [ ]:
df3

,연도,구분,1월,2월,3월,4월,5월,6월,7월,8월,9월,10월,11월,12월
0,2014,발생건수,4576,5935,9185,9776,9133,10384,9219,9666,10377,12035,9411,10412
1,2014,검거건수,3417,4238,5724,6235,6548,6328,6418,6102,7020,8329,5470,6121
2,2015,발생건수,11129,9223,13506,13794,12245,13650,13548,10904,11382,14617,10011,10670
3,2015,검거건수,6520,5360,9097,9987,9429,10323,9747,8971,8986,12721,6360,7387
4,2016,발생건수,10207,9974,13345,12658,17909,11103,12063,14631,13209,21085,7774,9117
5,2016,검거건수,7570,7768,11160,10789,15557,9075,10057,12909,11425,19278,5230,6940
6,2017,발생건수,9652,11706,13528,11493,11755,10367,10433,11317,11402,9551,11156,9374
7,2017,검거건수,7661,9924,11541,10307,10032,8194,8509,8753,9276,7844,8150,7298
8,2018,발생건수,11393,10031,12978,11894,11567,12361,13180,13420,12001,14562,14007,12210
9,2018,검거건수,8402,7742,10005,9357,8743,9299,9850,9615,9045,11501,10013,8561
10,2019,발생건수,14201,11115,14111,15534,15185,15807,17049,15057,13605,17987,15296,15552
11,2019,검거건수,9750,8332,10419,12152,11950,11735,12491,10909,10186,14247,10080,10308
12,2020,발생건수,14493,13756,18648,18705,17491,22854,21356,19015,24150,22283,18866,22481
13,2020,검거건수,8892,8594,12829,14816,12668,15798,14173,12438,16508,15078,12375,13740
14,2021,발생건수,11748,11181,15502,16961,15763,22329,18193,20192,19304,23779,22073,20782
15,2021,검거건수,6818,7962,10643,12324,10442,15703,11633,13233,13153,16099,11182,9518
16,2022,발생건수,19155,14274,19765,19733,19572,19390,19749,22112,21133,22389,15812,17271
17,2022,검거건수,10035,6911,10636,11702,13407,12294,12529,14408,17168,17764,7971,9060
18,2023,발생건수,19443,17228,20824,19488,24129,20821,20196,20233,20059,22288,18407,18727
19,2023,검거건수,9927,9955,12184,10768,13943,13602,10813,11868,12127,13555,10587,8901

In [ ]:
import pandas as pd

def safe_read_csv(file_path):
    """인코딩 에러를 방지하며 안전하게 CSV를 읽어오는 함수"""
    encodings = ['utf-8', 'cp949', 'utf-8-sig']
    for enc in encodings:
        try:
            return pd.read_csv(file_path, encoding=enc)
        except UnicodeDecodeError:
            continue
    raise ValueError(f"{file_path} 파일을 읽을 수 없습니다. 인코딩을 확인하세요.")

def run_simple_pipeline(monthly_file, content_file):
    print("🔄 데이터 파이프라인 가동 시작...")

    # ==========================================
    # 1. 월별 데이터 전처리
    # ==========================================
    try:
        df_monthly_raw = safe_read_csv(monthly_file)

        # 1월~12월 컬럼을 가로에서 세로(Row) 형태로 녹여내기
        month_cols = [f'{i}월' for i in range(1, 13)]
        melted_monthly = df_monthly_raw.melt(
            id_vars=['연도', '구분'],
            value_vars=month_cols,
            var_name='월',
            value_name='건수'
        )

        # '발생건수'와 '검거건수'를 별도의 컬럼으로 분리
        df_monthly_clean = melted_monthly.pivot_table(
            index=['연도', '월'],
            columns='구분',
            values='건수',
            aggfunc='sum'
        ).reset_index()

        # 정렬용 숫자 및 검거율 계산
        df_monthly_clean['월_숫자'] = df_monthly_clean['월'].str.replace('월', '').astype(int)
        df_monthly_clean['검거율(%)'] = (df_monthly_clean['검거건수'] / df_monthly_clean['발생건수'] * 100).round(2)
        df_monthly_clean = df_monthly_clean.sort_values(['연도', '월_숫자']).reset_index(drop=True)

        # 결과 저장
        df_monthly_clean.to_csv('정제된_월별_데이터.csv', index=False, encoding='utf-8-sig')
        print("✅ 1. 월별 데이터 정제 완료 -> '정제된_월별_데이터.csv' 저장됨")

    except Exception as e:
        print(f"❌ 월별 데이터 처리 중 오류 발생: {e}")

    # ==========================================
    # 2. 내용별(대그룹) 데이터 전처리
    # ==========================================
    try:
        df_content_raw = safe_read_csv(content_file)

        # 영문 컬럼명 한글로 표준화
        df_content_raw = df_content_raw.rename(columns={'Year': '연도', 'Type': '구분'})

        # 범죄 유형 컬럼들 추출 (Hacking, Scam, Cyber, Others 등)
        crime_types = [col for col in df_content_raw.columns if col not in ['연도', '구분']]

        # 가로 데이터를 세로 형태로 변환
        melted_content = df_content_raw.melt(
            id_vars=['연도', '구분'],
            value_vars=crime_types,
            var_name='범죄유형',
            value_name='건수'
        )

        # '발생건수'와 '검거건수'를 별도의 컬럼으로 분리
        df_content_clean = melted_content.pivot_table(
            index=['연도', '범죄유형'],
            columns='구분',
            values='건수',
            aggfunc='sum'
        ).reset_index()

        # 검거율 계산
        df_content_clean['검거율(%)'] = (df_content_clean['검거건수'] / df_content_clean['발생건수'] * 100).round(2)
        df_content_clean = df_content_clean.sort_values(['연도', '범죄유형']).reset_index(drop=True)

        # 결과 저장
        df_content_clean.to_csv('정제된_범죄내용별_데이터.csv', index=False, encoding='utf-8-sig')
        print("✅ 2. 범죄내용별 데이터 정제 완료 -> '정제된_범죄내용별_데이터.csv' 저장됨")

    except Exception as e:
        print(f"❌ 범죄내용별 데이터 처리 중 오류 발생: {e}")

# ==========================================
# 실행부 (파일명만 본인 파일명과 똑같이 맞춰주세요)
# ==========================================
monthly_csv_path = '경찰청_월별 사이버범죄 발생건수와 검거건수 현황_20231231 (1).csv'
content_csv_path = '경찰청_사이버범죄_대그룹_통합_추출.csv'

run_simple_pipeline(monthly_csv_path, content_csv_path)

🔄 데이터 파이프라인 가동 시작...
✅ 1. 월별 데이터 정제 완료 -> '정제된_월별_데이터.csv' 저장됨
✅ 2. 범죄내용별 데이터 정제 완료 -> '정제된_범죄내용별_데이터.csv' 저장됨

In [ ]:
import pandas as pd

def read_csv(file_path):
    """인코딩 문제를 방지하며 안전하게 CSV를 읽어오는 함수"""
    encodings = ['utf-8', 'cp949', 'utf-8-sig']
    for enc in encodings:
        try:
            return pd.read_csv(file_path, encoding=enc)
        except UnicodeDecodeError:
            continue
    raise ValueError(f"{file_path} 파일을 읽을 수 없습니다. 인코딩을 확인하세요.")

def clean_value(val):
    """숫자 데이터에 포함된 쉼표(,)를 제거하고 숫자로 변환하는 함수"""
    if pd.isna(val):
        return 0
    if isinstance(val, str):
        val = val.replace(',', '').strip()
    try:
        return int(float(val))
    except ValueError:
        return 0

def run_2017_pipeline(monthly_file, content_file):
    print("🔄 2017년 기준 데이터 파이프라인 가동 시작...")

    # ==========================================
    # 1. 월별 데이터 전처리 (2017년 이후 필터링)
    # ==========================================
    try:
        df_monthly_raw = safe_read_csv(monthly_file)

        # '연도' 컬럼을 숫자형으로 안전하게 변환
        df_monthly_raw['연도'] = df_monthly_raw['연도'].astype(int)

        # 🌟 2017년 이상인 데이터만 필터링
        df_monthly_raw = df_monthly_raw[df_monthly_raw['연도'] >= 2017]

        # 1월~12월 컬럼 추출 및 가로 데이터를 세로로 변환 (Melting)
        month_cols = [f'{i}월' for i in range(1, 13)]

        # 문자열 쉼표 제거 및 숫자 변환 적용
        for col in month_cols:
            df_monthly_raw[col] = df_monthly_raw[col].apply(clean_value)

        melted_monthly = df_monthly_raw.melt(
            id_vars=['연도', '구분'],
            value_vars=month_cols,
            var_name='월',
            value_name='건수'
        )

        # 발생건수와 검거건수를 컬럼으로 피벗
        df_monthly_clean = melted_monthly.pivot_table(
            index=['연도', '월'],
            columns='구분',
            values='건수',
            aggfunc='sum'
        ).reset_index()

        # 월 정렬 및 검거율 계산
        df_monthly_clean['월_숫자'] = df_monthly_clean['월'].str.replace('월', '').astype(int)
        df_monthly_clean['검거율(%)'] = (df_monthly_clean['검거건수'] / df_monthly_clean['발생건수'] * 100).round(2)
        df_monthly_clean['검거율(%)'] = df_monthly_clean['검거율(%)'].fillna(0) # 0 나누기 방지

        df_monthly_clean = df_monthly_clean.sort_values(['연도', '월_숫자']).reset_index(drop=True)

        # 컬럼 순서 이쁘게 정렬 및 저장
        df_monthly_clean = df_monthly_clean[['연도', '월', '월_숫자', '발생건수', '검거건수', '검거율(%)']]
        df_monthly_clean.to_csv('정제된_월별_데이터_2017이후.csv', index=False, encoding='utf-8-sig')
        print("✅ 1. 월별 데이터 정제 완료 -> '정제된_월별_데이터_2017이후.csv' 저장됨")

    except Exception as e:
        print(f"❌ 월별 데이터 처리 중 오류 발생: {e}")

    # ==========================================
    # 2. 내용별(대그룹) 데이터 전처리 (2017년 이후 필터링)
    # ==========================================
    try:
        df_content_raw = safe_read_csv(content_file)

        # 컬럼명 표준화 (Year -> 연도, Type -> 구분)
        df_content_raw = df_content_raw.rename(columns={'Year': '연도', 'Type': '구분'})
        df_content_raw['연도'] = df_content_raw['연도'].astype(int)

        # 🌟 2017년 이상인 데이터만 필터링
        df_content_raw = df_content_raw[df_content_raw['연도'] >= 2017]

        # 범죄 유형 컬럼들 (Hacking, Scam, Cyber, Others 등) 숫자 변환 적용
        crime_types = [col for col in df_content_raw.columns if col not in ['연도', '구분']]
        for col in crime_types:
            df_content_raw[col] = df_content_raw[col].apply(clean_value)

        # 가로 데이터를 세로 형태로 변환
        melted_content = df_content_raw.melt(
            id_vars=['연도', '구분'],
            value_vars=crime_types,
            var_name='범죄유형',
            value_name='건수'
        )

        # 발생건수와 검거건수를 컬럼으로 피벗
        df_content_clean = melted_content.pivot_table(
            index=['연도', '범죄유형'],
            columns='구분',
            values='건수',
            aggfunc='sum'
        ).reset_index()

        # 검거율 계산
        df_content_clean['검거율(%)'] = (df_content_clean['검거건수'] / df_content_clean['발생건수'] * 100).round(2)
        df_content_clean['검거율(%)'] = df_content_clean['검거율(%)'].fillna(0)

        df_content_clean = df_content_clean.sort_values(['연도', '범죄유형']).reset_index(drop=True)
        df_content_clean = df_content_clean[['연도', '범죄유형', '발생건수', '검거건수', '검거율(%)']]

        # 결과 저장
        df_content_clean.to_csv('정제된_범죄내용별_데이터_2017이후.csv', index=False, encoding='utf-8-sig')
        print("✅ 2. 범죄내용별 데이터 정제 완료 -> '정제된_범죄내용별_데이터_2017이후.csv' 저장됨")

    except Exception as e:
        print(f"❌ 범죄내용별 데이터 처리 중 오류 발생: {e}")

# ==========================================
# 실행 제어부 (파일명이 일치하는지 꼭 확인하세요!)
# ==========================================
monthly_csv_path = '경찰청_월별 사이버범죄 발생건수와 검거건수 현황_20231231 (1).csv'
content_csv_path = '경찰청_사이버범죄_대그룹_통합_추출.csv'

run_2017_pipeline(monthly_csv_path, content_csv_path)

🔄 2017년 기준 데이터 파이프라인 가동 시작...
✅ 1. 월별 데이터 정제 완료 -> '정제된_월별_데이터_2017이후.csv' 저장됨
✅ 2. 범죄내용별 데이터 정제 완료 -> '정제된_범죄내용별_데이터_2017이후.csv' 저장됨

In [ ]:
#머신러닝 과정과 결과
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

def safety_read_csv(file_path):
    encodings = ['utf-8', 'cp949', 'utf-8-sig']
    for enc in encodings:
        try: return pd.read_csv(file_path, encoding=enc)
        except UnicodeDecodeError: continue
    raise ValueError(f"{file_path} 파일을 읽을 수 없습니다.")

def final_value(val):
    if pd.isna(val): return 0
    if isinstance(val, str): val = val.replace(',', '').strip()
    try: return int(float(val))
    except ValueError: return 0

def run_perfect_ml_pipeline(monthly_file, content_file, predict_years=[2024, 2025, 2026]):
    print("🚀 머신러닝 예측 및 검거율 연산 파이프라인 가동...")

    # ==========================================
    # 1. 내용별(대그룹) 데이터 예측 (구조 전면 보정)
    # ==========================================
    df_content_raw = safe_read_csv(content_file)
    df_content_raw = df_content_raw.rename(columns={'Year': '연도', 'Type': '구분'})
    df_content_raw['연도'] = df_content_raw['연도'].astype(int)

    # 2017년 이후 데이터 필터링 및 쉼표 제거
    df_content_raw = df_content_raw[df_content_raw['연도'] >= 2017]
    crime_types = [col for col in df_content_raw.columns if col not in ['연도', '구분']]
    for col in crime_types:
        df_content_raw[col] = df_content_raw[col].apply(clean_value)

    # 가로 테이블 -> 세로 구조 가공
    melted_content = df_content_raw.melt(id_vars=['연도', '구분'], value_vars=crime_types, var_name='범죄유형', value_name='건수')

    # 발생/검거 피벗 및 인덱스 초기화
    df_content_clean = melted_content.pivot_table(index=['연도', '범죄유형'], columns='구분', values='건수', aggfunc='sum').reset_index()
    df_content_clean.columns.name = None

    # 실제 데이터 컬럼명 강제 지정
    df_content_clean = df_content_clean.rename(columns={'발생건수': '발생건수_실제', '검거건수': '검거건수_실제'})
    df_content_clean['검거율_실제(%)'] = np.where(df_content_clean['발생건수_실제'] > 0, (df_content_clean['검거건수_실제'] / df_content_clean['발생건수_실제'] * 100).round(2), 0.0)

    # 미래 예측 루프 수행
    future_records = []
    for c_type in df_content_clean['범죄유형'].unique():
        df_sub = df_content_clean[df_content_clean['범죄유형'] == c_type].sort_values('연도')

        # 데이터가 부족할 때를 대비해 가중치 부여 또는 기본 선형회귀 강제 매핑
        X_train = df_sub[['연도']].values
        y_inc = df_sub['발생건수_실제'].values
        y_arr = df_sub['검거건수_실제'].values

        # 모델 생성 및 학습
        model_inc = LinearRegression().fit(X_train, y_inc)
        model_arr = LinearRegression().fit(X_train, y_arr)

        for yr in predict_years:
            pred_inc_val = max(1, int(round(model_inc.predict([[yr]])[0]))) # 최소 1건 이상 나오도록 보정
            pred_arr_val = max(0, int(round(model_arr.predict([[yr]])[0])))

            # 검거건수가 발생건수보다 크게 나오는 현상 방지
            if pred_arr_val > pred_inc_val:
                pred_arr_val = int(pred_inc_val * 0.8)

            pred_rate = round((pred_arr_val / pred_inc_val * 100), 2)

            future_records.append({
                '연도': yr, '범죄유형': c_type,
                '발생건수_예측': pred_inc_val, '검거건수_예측': pred_arr_val, '예측검거율(%)': pred_rate
            })

    df_future_content = pd.DataFrame(future_records)

    # 실제 데이터와 예측 데이터 통합
    content_final = pd.concat([df_content_clean, df_future_content], ignore_index=True)
    content_final = content_final.sort_values(['연도', '범죄유형']).reset_index(drop=True)

    # 컬럼 배치 정렬
    content_cols = ['연도', '범죄유형', '발생건수_실제', '검거건수_실제', '검거율_실제(%)', '발생건수_예측', '검거건수_예측', '예측검거율(%)']
    content_final = content_final[content_cols]

    print("✅ 데이터 변환 및 머신러닝 예측 연산 완료!")
    return content_final

monthly_csv = '경찰청_월별 사이버범죄 발생건수와 검거건수 현황_20231231 (1).csv'
content_csv = '경찰청_사이버범죄_대그룹_통합_추출.csv'

# 파이프라인 실행 후 결과 변수에 담기
content_result = run_perfect_ml_pipeline(monthly_csv, content_csv)

🚀 머신러닝 예측 및 검거율 연산 파이프라인 가동...
✅ 데이터 변환 및 머신러닝 예측 연산 완료!

In [ ]:
content_result = content_result[(content_result['연도'].between(2024, 2027))]
display(content_result)

      연도     범죄유형  발생건수_실제  검거건수_실제  검거율_실제(%)   발생건수_예측   검거건수_예측  예측검거율(%)
28  2024    Cyber      NaN      NaN        NaN   38098.0   27732.0     72.79
29  2024  Hacking      NaN      NaN        NaN    2827.0     540.0     19.10
30  2024   Others      NaN      NaN        NaN  164024.0   83716.0     51.04
31  2024     Scam      NaN      NaN        NaN  207298.0  144802.0     69.85
32  2025    Cyber      NaN      NaN        NaN   40751.0   29594.0     72.62
33  2025  Hacking      NaN      NaN        NaN    2877.0     507.0     17.62
34  2025   Others      NaN      NaN        NaN  182790.0   91325.0     49.96
35  2025     Scam      NaN      NaN        NaN  211307.0  143574.0     67.95
36  2026    Cyber      NaN      NaN        NaN   43404.0   31455.0     72.47
37  2026  Hacking      NaN      NaN        NaN    2928.0     475.0     16.22
38  2026   Others      NaN      NaN        NaN  201556.0   98934.0     49.09
39  2026     Scam      NaN      NaN        NaN  215317.0  142346.0     66.11